import type { ToastState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: ToastState, fileName = "toast"): ExportPayload {
  return { fileName: `${fileName || "toast"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: ToastState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
    "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "function severityColor(s) { if (s.severity === \"success\") return s.successColor; if (s.severity === \"warning\") return s.warningColor; if (s.severity === \"error\") return s.errorColor; return s.infoColor; }",
    "function severitySurface(s, kind) {",
    "  const map = { info: { bg: s.infoBg, border: s.infoBorderColor }, success: { bg: s.successBg, border: s.successBorderColor }, warning: { bg: s.warningBg, border: s.warningBorderColor }, error: { bg: s.errorBg, border: s.errorBorderColor } };",
    "  const entry = map[s.severity];",
    "  if (!entry) return kind === \"bg\" ? s.toastBg : s.toastBorder;",
    "  return kind === \"bg\" ? entry.bg : entry.border;",
    "}",
    "",
    "const SEVERITY_ICONS = {",
    "  info: \"i\",",
    "  success: \"+\",",
    "  warning: \"!\",",
    "  error: \"!\",",
    "};",
    "",
    "export default function ToastComponent() {",
    "  const icon = SEVERITY_ICONS[state.severity] || SEVERITY_ICONS.info;",
    "  const accent = state.accent || severityColor(state);",
    "  const count = Math.max(1, Math.min(Math.max(1, Math.round(state.maxToasts)), Math.round(state.stackCount)));",
    "  const liveRole = state.role === \"alert\" || state.severity === \"error\" ? \"alert\" : \"status\";",
    "  const livePoliteness = liveRole === \"alert\" ? \"assertive\" : \"polite\";",
    "  const [actionHover, setActionHover] = React.useState(-1);",
    "  const [dismissHover, setDismissHover] = React.useState(-1);",
    "  const sevBorder = severitySurface(state, \"border\");",
    "  const variant = state.toastVariant;",
    "  const surfaceBg = variant === \"filled\" ? severitySurface(state, \"bg\") : state.toastBg;",
    "  const surfaceBorder = variant === \"filled\" || variant === \"outlined\" ? sevBorder : state.toastBorder;",
    "  const surfaceBorderWidth = variant === \"outlined\" ? Math.max(2, state.borderWidth) : state.borderWidth;",
    "",
    "  return (",
    "    <section id={state.id} role={state.role === \"region\" ? \"region\" : undefined} aria-label={state.ariaLabel} data-placement={state.placement} data-swipe-direction={state.swipeDirection} data-pause-on-hover={state.pauseOnHover} data-pause-on-window-blur={state.pauseOnWindowBlur} style={{ display: \"grid\", gap: state.stackGap, justifyItems: state.placement.includes(\"right\") ? \"end\" : \"start\" }}>",
    "      {Array.from({ length: count }, (_, index) => {",
    "        const scale = Math.max(0.8, 1 - index * state.stackScaleRatio);",
    "        return (",
    "        <article key={index} role={liveRole} aria-live={livePoliteness} aria-atomic=\"true\" tabIndex={state.disabled ? -1 : state.tabIndex} style={{",
    "          display: \"grid\",",
    "          gap: 12,",
    "          width: state.width,",
    "          minHeight: Math.max(92, Math.round(state.height / 3)),",
    "          padding: state.padding,",
    "          borderRadius: state.toastRadius,",
    "          border: surfaceBorderWidth + \"px \" + state.borderStyle + \" \" + (state.disabled && state.disabledUseCustomColors ? state.disabledBorder : surfaceBorder),",
    "          borderLeft: variant === \"left-accent\" ? \"4px solid \" + sevBorder : undefined,",
    "          boxShadow: state.toastShadow,",
    "          background: state.disabled && state.disabledUseCustomColors ? state.disabledBg : surfaceBg,",
    "          color: state.foreground,",
    "          fontFamily: resolveFont(state),",
    "          opacity: state.disabled || state.previewState === \"closed\" ? (state.disabledOpacity ?? 0.5) : 1,",
    "          transform: \"translate(\" + index * state.stackOffset + \"px, \" + index * state.stackOffset + \"px) scale(\" + scale + \")\",",
    "          transition: state.transitionDuration > 0 ? \"opacity 0.3s ease, transform 0.3s ease\" : \"none\",",
    "        }}>",
    "          <div style={{ display: \"flex\", alignItems: \"flex-start\", gap: 12 }}>",
    "            <span aria-hidden=\"true\" style={{ display: \"grid\", placeItems: \"center\", width: state.iconSize + 20, height: state.iconSize + 20, flexShrink: 0, borderRadius: 12, border: \"1px solid \" + state.iconColor, color: state.iconColor, fontWeight: 900 }}>{icon}</span>",
    "            <div style={{ display: \"grid\", gap: 4, flex: 1, minWidth: 0 }}>",
    "              <h3 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{index === 0 ? state.title : state.title + \" \" + (index + 1)}</h3>",
    "              <p style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "            </div>",
    "            {state.dismissible ? <button type=\"button\" disabled={state.disabled} aria-label=\"Dismiss toast\" onMouseEnter={() => setDismissHover(index)} onMouseLeave={() => setDismissHover(-1)} style={{ border: \"1px solid \" + state.dismissBorder, borderRadius: 12, padding: \"8px 12px\", background: dismissHover === index ? state.dismissHoverBg : \"transparent\", color: dismissHover === index ? state.dismissHoverColor : state.dismissColor }}>x</button> : null}",
    "          </div>",
    "          <div style={{ display: \"flex\", flexWrap: \"wrap\", justifyContent: \"space-between\", gap: 12, color: state.muted, fontSize: 12 }}><span>{state.helper}</span><span>{state.duration}ms{state.pauseOnHover ? \" · pause on hover\" : \"\"}</span></div>",
    "          {state.showAction ? <button type=\"button\" disabled={state.disabled} onMouseEnter={() => setActionHover(index)} onMouseLeave={() => setActionHover(-1)} style={{ justifySelf: \"start\", border: \"1px solid \" + state.actionBorder, borderRadius: 12, padding: \"8px 16px\", background: actionHover === index ? state.actionHoverBg : state.actionBg, color: state.actionText, fontWeight: 800 }}>{state.label}</button> : null}",
    "          {state.progressBarEnabled ? <div aria-hidden=\"true\" style={{ height: state.progressBarHeight, borderRadius: 999, background: state.progressBarBg, overflow: \"hidden\" }}><div style={{ height: \"100%\", width: \"62%\", background: state.progressBarColor }} /></div> : null}",
    "        </article>",
    "        );",
    "      })}",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
